/*
 * This Java source file was generated by avik.This project was built by me in 2018 for my school project.
 */
package SGame;

public class Main{    
   
    public static void main(String[] args) {
        
        SnakeGame ob=new SnakeGame(); 
        ob.load();
    }
}
